[metadata]
name = pybmd
version = attr: pybmd.__version__
description = Python Bispectral Mode Decomposition
long_description = file:README.md
long_description_content_type = text/markdown
author = Jun Hatayama
url = https://github.com/htymjun/PyBMD
license = MIT
license_files = LICENSE
keywords =
    BMD
    bispectral mode decomposition
    triadic interactions
    bispectrum
classifiers =
    Intended Audience :: Science/Research
    License :: OSI Approved :: MIT License
    Programming Language :: Python :: 3
    Topic :: Scientific/Engineering :: Mathematics

[options]
packages = find_namespace:
zip_safe = False
include_package_data = True
python_requires = >=3.9
install_requires =
    numpy
    scipy
    pyyaml
    matplotlib

[options.extras_require]
mpi = mpi4py >= 3.1
io =
    h5py
    netcdf4
    xarray
test =
    pytest
    pytest-cov
docs =
    Sphinx
    sphinx_rtd_theme

[coverage:run]
parallel = True
branch = True
source = pybmd
